## This file contains files and directories that should
## be preserved during an upgrade.

# /etc/example.conf
# /etc/openvpn/
/opt/p910nd_drivers
/etc/nginx/conf.d
/data/www/index.html
/etc/init.d/resize-root
/etc/init.d/resize2fs-root
/etc/init.d/tune-root
/etc/rc.d/S99resize-root
/etc/rc.local
/adguardhome/data/leases.json
/etc/config/adguardhome
/data/dtc
/boot/overlays/vl805-dma-fix-overlay.dtbo
/etc/sysctl.d/12-page.conf
/etc/init.d/custom-package-install
